### ISSUE TITLE
empirical EC model coefficients not specified

### ISSUE THREAD

**Issue by astranberg** [danielfppps/hydrobuddy#8]
Hello!

I'm reading on your linear regression model on the contribution of different ions to electrical conductivity to create an empirical model. It gives a very strong R2 but your file doesn't indicate the linear coefficients.

I took the liberty of downloading your .csv file and running the .py file. I'm a bit confused on the results, perhaps I'm doing it incorrectly:

```
>>> inputs
['N_NO3', 'N_NH4', 'Ca', 'S', 'K', 'P', 'Mg']
>>> m.coef_
array([ 0.40379135, -0.30896715, -0.28354946,  0.27611833, -0.11079075,
        0.14252525, -0.35878179])
>>> m.intercept_
0.3966167074820435
```

There shouldn't be negative numbers in here.

Either way, it appears you've already done it. I see the graph in your blog, but there's no precise numbers on the coefficients.

**Comment by danielfppps** [comment]
You are doing it correctly, your results match the coefficients that are actually loaded in the program for this model. When I posted the blog article I hadn't gathered all the experimental data, reason why the coefficients mismatch with what you got. 

The reason why the best linear fit is negative has to do with a couple of facts:

1. The model never sees the effect of adding or removing a single ion, but always cation/anion pairs. This means that the values are intrinsically tied together. The effect of these negative values never happens in isolation but as a consequence of the ion pair addition. For example take Mg and S. If you add MgSO4 you get 26.64% S and 20.19% Mg by mass. If you add the coefficient weighed by the mass contribution you get:

0.2664*0.276118 - 0.2019*0.358782
0.07355 - 0.07243
0.00112

These weighed contribution pairs are always positive. Because salt additions always cause increases in the conductivity. The model just never explicitly captures the effect of single ion additions, so these information is lacking in it.

2. The real relationship of the conductivity with the ion concentrations is related with the charge of the ions and the ionic strength of the solution. These are quite non-linear relationships but they can be expressed as negative coefficients for some individual elements IF you're always adding them in the same cation/anion pairs. See here https://www.aqion.de/site/77. 

Of course, this is counter-intuitive, but works really well in practice (you get a very simple model that works really well if you stay within the salt selection and concentration ranges tested). However, the interpretation of these coefficients as individual ion contributions to conductivity actually cannot be made, a mistake in my blog post.

I'm currently working on overhauling the LMC model in HydroBuddy to include the activity equations in the link I posted before, which allow for a much better estimation of conductivity in hydroponic solutions. 

I hope this helps. Thanks for your interest in the program!
